/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aahonacci.clock;
import java.awt.Color;
import java.util.Date;
import java.util.Random;
/**
 *
 * @author samsung
 */
public class front extends javax.swing.JFrame {

    /**
     * Creates new form front
     */
    public front() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f2 = new javax.swing.JButton();
        f3 = new javax.swing.JButton();
        f1 = new javax.swing.JButton();
        f11 = new javax.swing.JButton();
        f5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });

        f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(f3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f5, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f3, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
            .addComponent(f5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean runflag=false;
    int minof(int a,int b)
{
    if(a>b)
        return b;
    else return a;
}
int painttheboxes(int red,int blue,int green)
{
    int flag[] = new int[5];
    for(int i =0;i<5;i++)
        flag[i]=0;
    int last=red;
    int invalid=0;
    if(!(red>=0&&blue>=0&&green>=0))
        invalid =1;
    while(red>0&&invalid==0)
    {
        if(red>=5&&flag[4]==0){
            f5.setBackground(Color.red);
            red-=5;
            flag[4]=1;
        }
        else if(red>=3&flag[3]==0){
            f3.setBackground(Color.red);
            red-=3;
            flag[3]=1;
        }
        else if(red>=2&&flag[2]==0){
            f2.setBackground(Color.red);
            red-=2;
            flag[2]=1;
        }
         else if(flag[1]==0){
            f11.setBackground(Color.red);
            red-=1;
            flag[1]=1;
        }
        else{
            f1.setBackground(Color.red);
            red-=1;
            flag[0]=1;
        }
        if(last==red)
            invalid=1;
        last=red;
    }
    last = blue;
    while(blue>0&&invalid==0)
    {
        if(blue>=5&&flag[4]==0){
            f5.setBackground(Color.blue);
            blue-=5;
            flag[4]=1;
        }
        else if(blue>=3&flag[3]==0){
            f3.setBackground(Color.blue);
            blue-=3;
            flag[3]=1;
        }
        else if(blue>=2&&flag[2]==0){
            f2.setBackground(Color.blue);
            blue-=2;
            flag[2]=1;
        }
         else if(flag[1]==0){
            f11.setBackground(Color.blue);
            blue-=1;
            flag[1]=1;
        }
        else{
            f1.setBackground(Color.blue);
            blue -=1;
            flag[0]=1;
        }
        if(last==blue)
            invalid=1;
        last=blue;
    }
    last = green;
    while(green>0&&invalid==0)
    {
        if(green>=5&&flag[4]==0){
            f5.setBackground(Color.green);
            green-=5;
            flag[4]=1;
        }
        else if(green>=3&flag[3]==0){
            f3.setBackground(Color.green);
            green-=3;
            flag[3]=1;
        }
        else if(green>=2&&flag[2]==0){
            f2.setBackground(Color.green);
            green-=2;
            flag[2]=1;
        }
        else if(flag[1]==0){
            f11.setBackground(Color.green);
            green-=1;
            flag[1]=1;
        }
        else{
            f1.setBackground(Color.green);
            green-=1;
            flag[0]=1;
        }
        if(last==green)
            invalid=1;
        last=green;
    }
    if(invalid==0)
        runflag=true;
    return invalid;
}
    private void f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f5ActionPerformed
while(true)
{
f5.setBackground(null);
f3.setBackground(null);
f2.setBackground(null);
f11.setBackground(null);
f1.setBackground(null);
        Date date = new Date(System.currentTimeMillis());
        /*long i = System.currentTimeMillis();
long sec = i/1000;
long min = sec/60;
min+=30;
long hour = min/60;
hour+=5;
System.out.println(hour);
sec = sec%60;
min=min%60;
if(hour!=12)
    hour=hour%12;
System.out.println(hour+":"+min+":"+sec);
*/
        int timetosleep;
        Random ran = new Random();
        int hour = date.getHours();
        if(hour>12)
            hour%=12;
        int min = date.getMinutes();
        int sec = date.getSeconds();
        timetosleep = ((59-sec)%60)*1000;
        int red,blue,green,white;
        int i = 12- min/5;
        red = minof(hour,i);
        red = ran.nextInt(red+1);
        blue = hour - red;
        green = (min - 5*blue)/5;
        System.out.println("RED : "+red+"BLUE : "+blue+"GREEN : "+green);
        System.out.println(date.getHours()+":"+date.getMinutes()+":"+date.getSeconds());
        System.out.println(timetosleep);
        if(min-5*blue>=0)
       if(painttheboxes(red,blue,green)==0)break;/*{
           try{
           Thread.sleep(timetosleep);
           }catch(InterruptedException e)
           {
           //    continue;
           }
       }*/
}
 // TODO add your handling code here:
    }//GEN-LAST:event_f5ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
/*      while(true)
{
f5.setBackground(null);
f3.setBackground(null);
f2.setBackground(null);
f11.setBackground(null);
f1.setBackground(null);
        Date date = new Date(System.currentTimeMillis());
        /*long i = System.currentTimeMillis();
long sec = i/1000;
long min = sec/60;
min+=30;
long hour = min/60;
hour+=5;
System.out.println(hour);
sec = sec%60;
min=min%60;
if(hour!=12)
    hour=hour%12;
System.out.println(hour+":"+min+":"+sec);

        Random ran = new Random();
        int hour = 11;
        if(hour>12)
            hour%=12;
        int min = 35;
        int sec = date.getSeconds();
        int red,blue,green,white;
        int i = 12- min/5;
        red = minof(hour,i);
        red = ran.nextInt(red+1);
        blue = hour - red;
        green = (min - 5*blue)/5;
        System.out.println("RED : "+red+"BLUE : "+blue+"GREEN : "+green);
        System.out.println(hour+":"+min+":"+date.getSeconds());
       if(painttheboxes(red,blue,green)==0)
           break;
}*/  // TODO add your handling code here:
    }//GEN-LAST:event_f3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton f1;
    private javax.swing.JButton f11;
    private javax.swing.JButton f2;
    private javax.swing.JButton f3;
    private javax.swing.JButton f5;
    // End of variables declaration//GEN-END:variables
}
